const writeRomanNumerals = require("./index");

test("The function writeRomanNumerals exists", () => {
  expect(typeof writeRomanNumerals).toEqual("function");
});

test("Given the arabic number 7, return a 'dictionary' starting at '1' until '7' providing the equivalent in Roman Numerals.", () => {
  expect(writeRomanNumerals(7)).toEqual({
    1: "I",
    2: "II",
    3: "III",
    4: "IV",
    5: "V",
    6: "VI",
    7: "VII",
  });
});

test("Given the arabic number 68, return a 'dictionary' starting at '1' until '68' providing the equivalent in Roman Numerals.", () => {
  expect(writeRomanNumerals(68)).toEqual({
    1: "I",
    2: "II",
    3: "III",
    4: "IV",
    5: "V",
    6: "VI",
    7: "VII",
    8: "VIII",
    9: "IX",
    10: "X",
    11: "XI",
    12: "XII",
    13: "XIII",
    14: "XIV",
    15: "XV",
    16: "XVI",
    17: "XVII",
    18: "XVIII",
    19: "XIX",
    20: "XX",
    21: "XXI",
    22: "XXII",
    23: "XXIII",
    24: "XXIV",
    25: "XXV",
    26: "XXVI",
    27: "XXVII",
    28: "XXVIII",
    29: "XXIX",
    30: "XXX",
    31: "XXXI",
    32: "XXXII",
    33: "XXXIII",
    34: "XXXIV",
    35: "XXXV",
    36: "XXXVI",
    37: "XXXVII",
    38: "XXXVIII",
    39: "XXXIX",
    40: "XV",
    41: "XVI",
    42: "XVII",
    43: "XVIII",
    44: "XVIV",
    45: "XVV",
    46: "XVVI",
    47: "XVVII",
    48: "XVVIII",
    49: "XVIX",
    50: "L",
    51: "LI",
    52: "LII",
    53: "LIII",
    54: "LIV",
    55: "LV",
    56: "LVI",
    57: "LVII",
    58: "LVIII",
    59: "LIX",
    60: "LX",
    61: "LXI",
    62: "LXII",
    63: "LXIII",
    64: "LXIV",
    65: "LXV",
    66: "LXVI",
    67: "LXVII",
    68: "LXVIII",
  });
});
